version: '3'
services:
    web:
        build: .
        ports: 
         - "5000:5000"
        volumes:
         - .:/code
        depends_on:
         - db
    db:
        image: postgres
        volumes:
         - db-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        ports:
         - "5432:5432"
volumes:
  db-data:


